using Microsoft.AspNetCore.Hosting;
using TiendaApi.Helpers;

namespace TiendaApi.Services.Storage;

public class LocalStorageService : IStorageService
{
    private readonly string _basePath;
    private readonly string _baseUrl;

    public LocalStorageService(IConfiguration configuration, IWebHostEnvironment env)
    {
        var configuredPath = configuration["Storage:LocalPath"];
        _basePath = string.IsNullOrWhiteSpace(configuredPath)
            ? Path.Combine(env.WebRootPath ?? env.ContentRootPath, "uploads")
            : Path.GetFullPath(configuredPath);

        _baseUrl = "/uploads";
    }

    public async Task<string> UploadAsync(IFormFile file, string folder = "productos")
    {
        var folderPath = Path.Combine(_basePath, folder);
        Directory.CreateDirectory(folderPath);

        var extension = await ImageValidation.ValidateAsync(file);
        var filename = $"{Guid.NewGuid()}{extension}";
        var filePath = Path.Combine(folderPath, filename);

        using var stream = new FileStream(filePath, FileMode.Create);
        await file.CopyToAsync(stream);

        return $"{_baseUrl}/{folder}/{filename}";
    }

    public Task DeleteAsync(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
            return Task.CompletedTask;

        // Convert relative URL to file path. Only URLs generated by this
        // provider are accepted; an external URL must never be interpreted
        // as a local path.
        var cleanUrl = url.Split('?', 2)[0];
        var relativePath = cleanUrl.TrimStart('/').Replace('/', Path.DirectorySeparatorChar);
        var uploadsDir = "uploads" + Path.DirectorySeparatorChar;
        if (!relativePath.StartsWith(uploadsDir, StringComparison.OrdinalIgnoreCase))
            return Task.CompletedTask;

        var subPath = relativePath[uploadsDir.Length..];
        var basePath = Path.GetFullPath(_basePath);
        var filePath = Path.GetFullPath(Path.Combine(basePath, subPath));
        var basePathPrefix = basePath.EndsWith(Path.DirectorySeparatorChar)
            ? basePath
            : basePath + Path.DirectorySeparatorChar;

        if (!filePath.StartsWith(basePathPrefix, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("La ruta de la imagen está fuera del almacenamiento configurado.");

        if (File.Exists(filePath))
        {
            File.Delete(filePath);
        }

        return Task.CompletedTask;
    }
}
